<a href="https://colab.research.google.com/github/JayGhiya/DataScience/blob/master/tensor_operations_assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PYTORCH101**  

### *Tensors*

An short introduction about PyTorch and about the chosen functions. 
- torch.as_tensor(data, dtype=None, device=None) → Tensor
- function 2
- function 3
- function 4
- function 5

In [0]:
# Import torch and other required modules
import torch
import numpy

## Function 1 - torch.as_tensor(data, dtype=None, device=None) → Tensor

Converts the data into a torch tensor. If the data is an ndarray of the corresponding dtype and the device is CPU, no copy will be performed.

In [17]:
# Example 1 - working (change this)
np_array = numpy.array([[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
t_1 = torch.as_tensor(data = np_array , device=torch.device('cpu')) 
t_1.size(),t_1

(torch.Size([3, 3]), tensor([[ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]], dtype=torch.float64))

Now let us try to modify the tensor using indexing of numpy arrays and see the change in original numpy array. 

In [18]:
# Example 2 - working
t_1[0][0] = 10
np_array

array([[10.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

Torch as tensor api supports building tensor from tuple,list,ndarray and scalar but not set. As set does not support duplicate values which may be part of tensor and needed for further computation.

In [13]:
# Example 3 - breaking (to illustrate when it breaks)
torch.as_tensor({1,23,3,4})

RuntimeError: ignored

To summarize we have used torch.as_tensor to generate a tensor out of numpy array without copying the data of numpy array by saving space. Also we saw how modifying tensor automatically modifies the numpy array which is a handy thing as we can do direct visualizations on numpy array using matplotlib lib after using operations on tensor.

torch.tensor() always copies data. If you have a Tensor data and just want to change its requires_grad flag, use requires_grad_() or detach() to avoid a copy. If you have a numpy array and want to avoid a copy, use torch.as_tensor().

```
# reference:  https://pytorch.org/docs/stable/torch.html#torch.as_tensor
```



## Function 2 - torch.stack(tensors, dim=0, out=None) → Tensor
It adds new tensors along a new dimension. Now let us try to add a tensor using stack to existing tensor t_1. We will use torch.from_numpy() to generate a new tensor and then use torch.stack() to perform the stack operation along dimension 0.




In [23]:
# Example 1 - working
t_2 = torch.from_numpy(numpy.array([[1.,8.,10.],[12.,14.,16.],[19.,20.,25.]]))
t_2
t_3 = torch.stack([t_1,t_2])
t_3,t_3.size()

(tensor([[[10.,  5.,  6.],
          [ 7.,  8.,  9.],
          [10., 11., 12.]],
 
         [[ 1.,  8., 10.],
          [12., 14., 16.],
          [19., 20., 25.]]], dtype=torch.float64), torch.Size([2, 3, 3]))

The stack function can be used when we are training on a batch of say 2d images which will have 2 dimensions. So what batch operation will do is stack n number of images along 0 dimension for that batch and then iterate over that dimension to get list of images.



In [27]:
# Example 2 - working
for image in t_3:
  #do training
  print(image)

tensor([[10.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]], dtype=torch.float64)
tensor([[ 1.,  8., 10.],
        [12., 14., 16.],
        [19., 20., 25.]], dtype=torch.float64)


As we are stacking tensors along dimension 0 it is important to understand that tensors that need to be stacked have to be of same operation. if they are not then error will be thrown stating dimensions are not of same size.

In [32]:
# Example 3 - breaking (to illustrate when it breaks)
t_4 = torch.from_numpy(numpy.array([[1.,8.,10.,11.],[12.,14.,16.,17.],[19.,20.,25.,26.]]))
t_5 = torch.stack([t_1,t_4])

RuntimeError: ignored

Here we saw how stack operation of tensor can be used to load multiple examples of same tensor size across a new dimension which is zero by default.


```
# reference: https://pytorch.org/docs/master/generated/torch.stack.html
```



It can be used when we are training with multiple examples. For instance can be used to stack 2d images.

## Function 3 - ???

Add some explanations

In [0]:
# Example 1 - working

Explanation about example

In [0]:
# Example 2 - working

Explanation about example

In [0]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

## Function 4 - ???

Add some explanations

In [0]:
# Example 1 - working

Explanation about example

In [0]:
# Example 2 - working

Explanation about example

In [0]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

## Function 5 - ???

Add some explanations

In [0]:
# Example 1 - working

Explanation about example

In [0]:
# Example 2 - working

Explanation about example

In [0]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [28]:
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 92kB 2.3MB/s 


In [0]:
import jovian

In [31]:
jovian.commit()

[jovian] Error: Failed to detect Jupyter notebook or Python script. Skipping..
